[package]
name = "cammy"
version = "0.1.0"
edition = "2024"

[dependencies]
app_dirs2 = "2.5.5"
dashmap = "6.1.0"
fnv = "1.0.7"
num_cpus = "1.17.0"

[dependencies.chrono]
version = "0.4.42"
default-features = false
features = ["alloc", "std", "clock", "now"]
